[package]
name = "crate"
version = "0.1.0"
authors = ["Nick Babcock <nbabcock19@hotmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.100"
brotli = "5.0.0"

[package.metadata.wasm-pack.profile.release]
wasm-opt = false
