[tools]
"node" = { version = "22.18.0" }
"ubi:rustwasm/wasm-bindgen" = { version = "0.2.100", extract_all = "true" }
"ubi:WebAssembly/binaryen" = { version = "version_123", extract_all = "true", bin_path = "bin" }

[tasks."build:wasm"]
run = [
    "cargo build --release -p crate --target wasm32-unknown-unknown",
    "wasm-bindgen --out-dir ./src/brotli/crate/pkg --target web ./target/wasm32-unknown-unknown/release/crate.wasm",
    "wasm-opt -Os -o ./src/brotli/crate/pkg/crate_bg.wasm ./src/brotli/crate/pkg/crate_bg.wasm",
]
