name: CI

on:
  pull_request:
  push:
  schedule:
  - cron: '00 01 01 * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install wasm-pack
      run:  npm install -g wasm-pack@0.10.1
    - name: npm install, build, and test
      run: |
        npm install
        npm run build
        npm test
      env:
        CI: true
