name: CI

on:
  pull_request:
  push:
  schedule:
  - cron: '00 01 01 * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: jdx/mise-action@v2
    - run: rustup target add wasm32-unknown-unknown
    - run: mise run build:wasm
    - name: npm ci, build, and test
      run: |
        npm ci
        npm run build
        npm test
      env:
        CI: true
